# M1b-1 level executor: mechanically executes the C++-generated build plan.
#
# The plan (Data/Reports/workroom_001.plan.json) is produced by
# FLevelPlanBuilder from the VALIDATED SceneSpec; every coordinate, size and
# rotation is already resolved in C++ using the M1a coordinate convention.
# This script performs NO SceneSpec interpretation - it only creates the
# listed ops and saves the level.
#
# Run via the GUI editor (commandlet mode crashes in LevelEditorSubsystem):
#   UnrealEditor.exe WorldGen.uproject -ExecutePythonScript="<this file>" -abslog="<log>"
# The script quits the editor itself when done.
import unreal

# Public-repo path resolution: derive every on-disk path from the UE
# project directory. (The original local build hardcoded absolute E:/
# paths; see README -> "Differences from the internal version".)
_ROOT = unreal.Paths.project_dir()
if not _ROOT.endswith(("/", "\\")):
    _ROOT += "/"
import json
import os
import sys

# M3a: materials are assigned by the builder itself, so any rebuild reproduces
# the look (no manual editor work is ever required).
sys.path.append(_ROOT + "Tools")
import wg_matlib  # noqa: E402

REPORTS_DIR = _ROOT + "Data/Reports"
# M1c: the generator writes m1b_current_plan.txt (one line = plan path) so this
# executor can build ANY AI-generated scene, not only workroom_001.
POINTER_PATH = os.path.join(REPORTS_DIR, "m1b_current_plan.txt")
DEFAULT_PLAN = os.path.join(REPORTS_DIR, "workroom_001.plan.json")
if os.path.isfile(POINTER_PATH):
    with open(POINTER_PATH, "r") as pf:
        _p = pf.read().strip()
    PLAN_PATH = _p if _p else DEFAULT_PLAN
else:
    PLAN_PATH = DEFAULT_PLAN
MANIFEST_PATH = os.path.join(REPORTS_DIR, "m1b_actors_manifest.json")
CUBE = "/Engine/BasicShapes/Cube.Cube"
# M2b: the plan's object box ops carry the SceneSpec asset_id; the asset
# manifest maps asset_id -> imported UE static mesh generated by Hunyuan3D-2.1.
# Missing/unready asset_ids fall back to the placeholder cube and the fallback
# is logged with the object id, asset_id and reason (M2B FALLBACK / PLACEHOLDER).
ASSET_MANIFEST_PATH = _ROOT + "Data/Assets/asset_manifest.json"


def load_asset_manifest():
    # M2b: assets are resolved by the asset_id carried in the PLAN op
    # (SceneSpec objects[].asset_id), never by the spec object id. Returns
    # ({asset_id: entry} for ready assets, {asset_id: status} for all).
    if not os.path.isfile(ASSET_MANIFEST_PATH):
        return {}, {}
    with open(ASSET_MANIFEST_PATH, "r") as f:
        mf = json.load(f)
    ready, statuses = {}, {}
    for a in mf.get("assets", []):
        aid = a.get("asset_id")
        if not aid:
            continue
        statuses[aid] = a.get("status", "?")
        if a.get("status") == "ready":
            ready[aid] = a
    return ready, statuses


def resolve_spec_id(op_name):
    # ops name objects "WG_obj_<spec_id>"; strip the prefix
    if op_name.startswith("WG_obj_"):
        return op_name[len("WG_obj_"):]
    return None


def log(msg):
    unreal.log("[M1bLevelBuilder] " + msg)


def main():
    with open(PLAN_PATH, "r") as f:
        plan = json.load(f)
    level_path = plan["level_path"]
    log("plan loaded: scene=%s ops=%d" % (plan["scene_id"], len(plan["ops"])))

    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    actor_sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    ready_assets, asset_statuses = load_asset_manifest()

    # Idempotency: never stack on a previous run - rebuild from scratch.
    if unreal.EditorAssetLibrary.does_asset_exist(level_path):
        ok = unreal.EditorAssetLibrary.delete_asset(level_path)
        log("deleted existing level %s -> %s" % (level_path, ok))
        if not ok:
            raise RuntimeError("could not delete existing level " + level_path)

    if not les.new_level(level_path):
        raise RuntimeError("new_level failed: " + level_path)
    log("new blank level created: " + level_path)

    for op in plan["ops"]:
        kind = op["op"]
        name = op["name"]
        loc = op["location_cm"]
        yaw = float(op.get("yaw_deg", 0.0))
        rot = unreal.Rotator(0.0, 0.0, yaw)  # (roll, pitch, yaw)

        if kind == "box":
            size = op["size_cm"]
            scale = (size[0] / 100.0, size[1] / 100.0, size[2] / 100.0)
            spec_id = resolve_spec_id(name)  # object id, for logging only
            asset_id = op.get("asset_id", "")
            mesh = None
            ue_path = None
            if asset_id == "placeholder" or asset_id == "key_placeholder":
                log("M2B PLACEHOLDER: object '%s' explicitly requests asset_id='%s'; "
                    "using placeholder cube" % (name, asset_id))
            elif asset_id:
                asset_entry = ready_assets.get(asset_id)
                if asset_entry is not None:
                    ue_path = asset_entry.get("ue_asset_path")
                    mesh = unreal.EditorAssetLibrary.load_asset(ue_path) if ue_path else None
                    if mesh is None:
                        log("M2B FALLBACK: object '%s' asset_id='%s' -> registered but UE "
                            "asset '%s' failed to load; using placeholder cube"
                            % (name, asset_id, ue_path))
                elif asset_id in asset_statuses:
                    log("M2B FALLBACK: object '%s' asset_id='%s' -> registered with "
                        "status '%s' (not ready); using placeholder cube"
                        % (name, asset_id, asset_statuses[asset_id]))
                else:
                    log("M2B FALLBACK: object '%s' asset_id='%s' -> NOT registered in "
                        "%s; using placeholder cube" % (name, asset_id, ASSET_MANIFEST_PATH))
            else:
                log("M2B PLACEHOLDER: box '%s' carries no asset_id (structural box); "
                    "using placeholder cube" % name)
            actor = actor_sub.spawn_actor_from_class(
                unreal.StaticMeshActor, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
            if mesh is not None:
                # Generated mesh: pivot is bottom center, so place the actor at
                # the box's bottom face (loc.z is the box center z).
                actor.set_actor_location(
                    unreal.Vector(loc[0], loc[1], loc[2] - size[2] / 2.0), False, False)
                log("M2B HIT: object '%s' (object_id=%s) uses generated asset %s "
                    "(asset_id=%s)" % (name, spec_id, ue_path, asset_id))
                actor.get_editor_property("static_mesh_component").set_static_mesh(mesh)
                # Equivalent simple-box collision of the spec footprint keeps
                # blocking behaviour identical to the placeholder cube.
                # UE5.7: 'collision_profile_name' is not an exposed property;
                # SetCollisionProfileName is the UFUNCTION entry point.
                mesh_comp = actor.get_editor_property("static_mesh_component")
                mesh_comp.set_collision_profile_name("BlockAll")
            else:
                actor.set_actor_scale3d(unreal.Vector(*scale))
                actor.get_editor_property("static_mesh_component").set_static_mesh(
                    unreal.EditorAssetLibrary.load_asset(CUBE))
        elif kind == "player_start":
            actor = actor_sub.spawn_actor_from_class(
                unreal.PlayerStart, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
        elif kind == "door":
            actor = actor_sub.spawn_actor_from_class(
                unreal.WorldGenDoor, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
        elif kind == "pickup":
            actor = actor_sub.spawn_actor_from_class(
                unreal.WorldGenPickup, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
        elif kind == "exit_trigger":
            actor = actor_sub.spawn_actor_from_class(
                unreal.WorldGenExitTrigger, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
        elif kind == "directional_light":
            pitch = float(op.get("pitch_deg", -55.0))
            actor = actor_sub.spawn_actor_from_class(
                unreal.DirectionalLight, unreal.Vector(*loc),
                unreal.Rotator(0.0, pitch, yaw))
            actor.set_actor_label(name)
        elif kind == "sky_light":
            actor = actor_sub.spawn_actor_from_class(
                unreal.SkyLight, unreal.Vector(*loc), rot)
            actor.set_actor_label(name)
            try:
                comp = actor.get_editor_property("light_component")
                comp.set_editor_property("b_real_time_capture", True)
            except Exception as e:
                log("sky light real-time capture not set: %s" % e)
        else:
            raise RuntimeError("unknown op: " + kind)
        log("executed %s %s at %s yaw=%.1f" % (kind, name, loc, yaw))

    # M3a: apply the generated materials (triplanar wood/plaster/concrete/etc.)
    # before saving, so the level is never saved as a white model.
    try:
        wg_matlib.apply_scene_materials(plan["scene_id"], actor_sub)
    except Exception as e:  # noqa: BLE001
        log("MATERIAL ASSIGNMENT FAILED: %s: %s" % (type(e).__name__, e))

    if not les.save_current_level():
        raise RuntimeError("save_current_level failed")
    log("level saved: " + level_path)

    # Manifest for the two-run determinism comparison.
    entries = []
    for a in actor_sub.get_all_level_actors():
        loc = a.get_actor_location()
        rot = a.get_actor_rotation()
        scl = a.get_actor_scale3d()
        entries.append({
            "label": a.get_actor_label(),
            "class": a.get_class().get_name(),
            "location": [round(loc.x, 2), round(loc.y, 2), round(loc.z, 2)],
            "rotation": [round(rot.roll, 2), round(rot.pitch, 2), round(rot.yaw, 2)],
            "scale": [round(scl.x, 4), round(scl.y, 4), round(scl.z, 4)],
        })
    entries.sort(key=lambda e: e["label"])
    with open(MANIFEST_PATH, "w") as f:
        json.dump({"level_path": level_path, "actor_count": len(entries),
                   "actors": entries}, f, indent=1, sort_keys=True)
    log("manifest written: %d actors -> %s" % (len(entries), MANIFEST_PATH))

    unreal.SystemLibrary.quit_editor()


main()
