#!/usr/bin/env python3
# M3a: build a simple stylized KEY prop mesh (replaces the placeholder sphere
# that made the quest key look like a white ball in previews).
#
#   Tools/hy3d_env/Scripts/python.exe Tools/m3a_make_key.py
#
# Units: centimetres, UE convention (X forward, Y right, Z up). ~26 cm long.
# Output: Data/Assets/m3a/key/SM_Key_Prop.obj (+ provenance note).
import os

import numpy as np
import trimesh

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                   "Data", "Assets", "m3a", "key")
os.makedirs(OUT, exist_ok=True)

# ---- ring head: annulus in the X-Z plane (torus axis = Y), centred at origin
head = trimesh.creation.annulus(r_min=3.2, r_max=6.5, height=1.3, sections=32)
head.apply_transform(trimesh.transformations.rotation_matrix(np.pi / 2, [1, 0, 0]))

# ---- shaft: from the ring to the tip, slightly thinner than the ring
shaft = trimesh.creation.box(extents=[19.0, 1.5, 1.5])
shaft.apply_translation([14.0, 0.0, 0.0])          # x 4.5 .. 23.5

# ---- collar where shaft meets ring (a touch wider, reads as the key neck)
collar = trimesh.creation.box(extents=[3.0, 1.9, 1.9])
collar.apply_translation([6.5, 0.0, 0.0])

# ---- two teeth hanging below the shaft near the tip
tooth1 = trimesh.creation.box(extents=[2.6, 1.5, 3.4])
tooth1.apply_translation([19.6, 0.0, -2.2])
tooth2 = trimesh.creation.box(extents=[3.4, 1.5, 2.4])
tooth2.apply_translation([22.0, 0.0, -1.7])

key = trimesh.util.concatenate([head, shaft, collar, tooth1, tooth2])
# drop the annulus cap triangles so the ring reads as a ring (annulus is
# already open-ended, nothing to do) -- just export.
path = os.path.join(OUT, "SM_Key_Prop.obj")
key.export(path)
print("verts", len(key.vertices), "faces", len(key.faces))
print("bounds", key.bounds.tolist())
print("written", os.path.abspath(path))
with open(os.path.join(OUT, "provenance.json"), "w", encoding="utf-8") as f:
    f.write("""{
 "asset": "SM_Key_Prop",
 "source": "procedural, generated by Tools/m3a_make_key.py (trimesh primitives: annulus + boxes)",
 "license": "project-owned, no third-party content",
 "size_cm": "26 x 13 x 9 approx (length x ring diameter x incl. teeth)",
 "purpose": "visual mesh for WorldGenPickup.KeyMesh (replaces /Engine/BasicShapes/Sphere placeholder)"
}
""")
